### ISSUE TITLE
Pipelines as code example does not save

### ISSUE THREAD

**Issue by sghill** [gocd/docs.go.cd#110]
The [Pipelines as code][pac] section has this example code (and a similar block for JSON) which does not save on GoCD 17.8.0:

```xml
<config-repos>
    <config-repo plugin="yaml.config.plugin">
        <git url="https://github.com/tomzo/gocd-yaml-config-example.git" />
    </config-repo>
</config-repos>
```

Error:
<img width="690" alt="gocd-id-is-required" src="https://user-images.githubusercontent.com/230004/29827132-f7986fde-8c8d-11e7-9a4d-c3ac89a8d474.png">

I updated the element to `<config-repo plugin="yaml.config.plugin" id="myreponame">` and it worked, but it'd be great if this was present in the docs. Happy to submit a PR for this, but is there a preferred value for the id? Or just any unique string?

[pac]: https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html#storing-pipeline-configuration-in-yaml

**Comment by ketan** [comment]
A unique string is what is expected. Would appreciate if you could update the example and the reference doc (https://docs.gocd.org/current/configuration/configuration_reference.html#config-repo).

Thanks.

**Comment by varshavaradarajan** [comment]
@sghill, thanks for reporting the issue. The id must be a unique alphanumeric string. It can also contain `-`,` _`,` .` Can you also update the plugin attribute to be `pluginId`?

**Comment by arvindsv** [comment]
Based on [this](https://github.com/gocd/gocd/blob/0f72f2664b89f8587aac6e7da9bb16148fd3132d/config/config-api/src/com/thoughtworks/go/config/remote/ConfigRepoConfig.java#L54), I thought the ID would be generated if not present. Why isn't that the case? /cc @GaneshSPatil

**Comment by sghill** [comment]
@varshavaradarajan I tried saving `<config-repo pluginId="yaml.config.plugin" id="my-ci-config">` and got this error:

> Attribute 'pluginId' is not allowed to appear in element 'config-repo'.

**Comment by varshavaradarajan** [comment]
@sghill , the attribute `plugin` was changed to `pluginId` for the release 17.9.0 I think. You can verify it with one of the experimental releases from https://www.gocd.org/download/?experimental=true. Sorry, I thought that the document wasn't updated for 17.8.0.

**Comment by sghill** [comment]
@varshavaradarajan thanks for the clarification! Since the docs are also versioned, maybe we should leave that out until 17.9.0 is released?

@arvindsv sounds like this might be an implementation bug instead of a docs bug?

**Comment by GaneshSPatil** [comment]
@arvindsv @sghill -- `id` field on *config repo* is mandatory as of release `17.8.0`.
This error is thrown due to xsd validations.
Related code:
[XsdErrorTranslator](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/util/XsdErrorTranslator.java#L47-L50)
[config repo id attribute](https://github.com/gocd/gocd/blob/master/config/config-server/resources/cruise-config.xsd#L155)

**Comment by arvindsv** [comment]
@GaneshSPatil If so, the doc page for 17.8 needs to be updated: https://docs.gocd.org/17.8.0/advanced_usage/pipelines_as_code.html#storing-pipeline-configuration-in-yaml

Also, I thought that the ID was auto generated. Why is that not the case?

**Comment by GaneshSPatil** [comment]
@arvindsv -- Yes, the docs need to be updated for `id` as well as `pluginId` attributes of config-repo. Issue link: https://github.com/gocd/gocd/issues/3671#issuecomment-326332392

`id` attribute on `Config repo` tag was added as part of GoCD version `17.8.0`.
So, if someone upgrades from older version to `17.8.0` or above, [`xsl migration`](https://github.com/gocd/gocd/blob/master/config/config-server/resources/upgrades/94.xsl) will add the missing id attribute on it (which will be a random string).

But from `17.8.0`, if a new `config-repo` tag needs to be added, `id` field is mandatory.

**Comment by varshavaradarajan** [comment]
@arvindsv , the auto generation of id happens for entities like scms, package repos. But it doesn't happen on newer entities. Like auth config, role config, etc. We need to make it consistent whichever way. I think that autogeneration should be supported on newer entities if the user doesn't provide one. @GaneshSPatil ?

**Comment by arvindsv** [comment]
Yes, I think it should be consistent and it should be generated. If the client-side wants to provide it (and it is valid in that context), that's ok too.
