### ISSUE TITLE
Documentation for configuring agent server bind port for Agent Health Check AP

### ISSUE THREAD

**Issue by adityasood** [gocd/docs.go.cd#125]
**Summary**

Documentation required for specifying agent server bind port ( defaults to 8152 ) but is configurable and this needs to be documented.

**Basic environment details**

Go Version: 17.11.0
JAVA Version: JAVA8
OS: NA
Browser vendor and version (if relevant):NA

**Steps to Reproduce**

1. Register multiple agents from the same machine
2. Use agent health check API to check for agent health
3. Bring down the first registered agent
4. Check for second agent health

**Expected Results**

User should have the information about the configurable port

**Actual Results**

Currently, the documentation is missing

**Comment by tedder** [comment]
For those following along, it appears this is set in the server config, not in the agent config (e.g., it doesn't go in `/etc/default/go-agent*`).

**Comment by tedder** [comment]
that's wrong. It goes in there:
```
GO_AGENT_SYSTEM_PROPERTIES="-Dgo.agent.status.api.bind.port=6666"
```

Compare and contrast that to the bootstrapper args:
```
AGENT_BOOTSTRAPPER_ARGS="-sslVerificationMode NONE"
GO_AGENT_SYSTEM_PROPERTIES="-Dgo.agent.status.api.bind.port=6666"
```
