### ISSUE TITLE
minikube instructions start minikube twice

### ISSUE THREAD

**Issue by kmugrage** [gocd/docs.go.cd#176]
In https://docs.gocd.org/18.3.0/gocd_on_kubernetes/gocd_helm_chart/configure_cluster.html#configure-service-account instructions are given for starting the cluster with kubeadm. If following the getting started from the beginning the cluster has already been started at https://docs.gocd.org/18.3.0/gocd_on_kubernetes/gocd_helm_chart/setup.html#2-setup-a-kubernetes-cluster

**Comment by varshavaradarajan** [comment]
Fixed via 1aa8e16b94575184ac583da551bb87ff2514babb
