### ISSUE TITLE
Update pipelines as code page

### ISSUE THREAD

**Issue by ankitsri11** [gocd/docs.go.cd#242]
https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html

**Comment by ankitsri11** [comment]
Raised this PR: https://github.com/gocd/docs.go.cd/pull/247

**Comment by adityasood** [comment]
@ankitsri11 I see the above PR is merged, if nothing is pending on this can we close this issue?

**Comment by ankitsri11** [comment]
Updates are available here: https://docs.gocd.org/19.3.0/advanced_usage/pipelines_as_code.html
