### ISSUE TITLE
Implement search functionality for docs website

### ISSUE THREAD

**Issue by SanjanaB** [gocd/docs.go.cd#245]

**Comment by SanjanaB** [comment]
Implemented search using lunrjs. Created a PR for the same [https://github.com/gocd/docs.go.cd/pull/241] UI styling is pending.
Lunr provides basic stemming, stopword filter. Further finetuning can be done after testing is done.

**Comment by arvindsv** [comment]
@kritika-singh3 After #250, some search results show "undefined". See this:

<img width="1149" alt="2019_03_08_05-39-59" src="https://user-images.githubusercontent.com/172235/53998166-c76f3580-4164-11e9-809a-9f0ef2fae756.png">

**Comment by kritika-singh3** [comment]
@arvindsv I'll look into it
