### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by kierarad** [gocd/docs.go.cd#285]
Link to GoCD Server installation instructions from https://docs.gocd.org/current/installation/ is incorrect and leaves 404 error.

```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: current/installation/installation/installing_go_server.html
RequestId: 97C3C9BE24A91554
HostId: jtNesGtHcxODA+YzdX5DX+qsnM7oV0ghKNFTm571/a1heQucPikGbHzsoIKGL4TLRJMAh7gPgK8=
```

**Comment by hellupline** [comment]
the current URL for installation instructions is set to 
`https://docs.gocd.org/current/installation/installation/installing_go_server.html`

I think the intented URL is 
`https://docs.gocd.org/current/installation/installing_go_server.html`

**Comment by hellupline** [comment]
oh, you were faster than me :D
https://github.com/gocd/docs.go.cd/pull/287 ( had to wait the end of my shift )
