### ISSUE TITLE
Wrong documentation found in proxy section

### ISSUE THREAD

**Issue by sitzmoebelchronograph** [gocd/docs.go.cd#362]
Hey guys

on this page https://docs.gocd.org/current/installation/configure-agent-proxy.html are 2 typos.

# the proxy port
wrapper.java.additional.101-Dhttps.proxyPort=3128 ## WRONG
wrapper.java.additional.101=-Dhttps.proxyPort=3128 ## RIGHT

# do not proxy connections to these hosts
wrapper.java.additional.102-Dhttp.nonProxyHosts=localhost|*.department.acme.com ## WRONG
wrapper.java.additional.102=-Dhttp.nonProxyHosts=localhost|*.department.acme.com ## RIGHT

Invest 30 minutes of debug to find the issue there /o\.

Maybe it's possible to fix it :)

Greets
Andreas

**Comment by ketan** [comment]
Thanks, I've fixed this, the docs site should be updated in a few mins from now.
