### ISSUE TITLE
Using an environment variable as the value to set another environment variable.

### ISSUE THREAD

**Issue by thebrandonhoward** [gocd/docs.go.cd#431]
On a job level environment variable configuration:

The following works when using parameters passed from another pipleline to my template:
Environment Variables
Name                              Value
BRANCH                         #{PIPELINE_BRANCH}_INDEX

However, this does not.
Name                              Value
BRANCH                         ${STAGE_LEVEL_ENVIRONMENT_VARIABLE}_INDEX

in the latter case, it takes the literal value without replacing with the environment variable

**Comment by arvindsv** [comment]
@thebrandonhoward Yes, that is intentional. GoCD won't interpolate environment variables. You'll need to use something like: `bash -c` in a task, to do that.

**Comment by arvindsv** [comment]
This has been brought up elsewhere. For instance: https://groups.google.com/g/go-cd/c/eLun39KkxhQ/m/5hE_BHylBAAJ

**Comment by thebrandonhoward** [comment]
OK. Closed case then.
