### ISSUE TITLE
Beta feature: Upload plugins property is incorrect

### ISSUE THREAD

**Issue by jaymed** [gocd/docs.go.cd#46]
The following page shows that `**GO_SERVER_SYSTEM_PROPERTIES**`should be set to `-Dgo.plugin.upload.enabled=true`. This does not seem to work for me, but @varshavaradarajan provided the following value which does work: `-Dgo.plugin.upload.enabled=Y` ([thread](https://github.com/gocd/docs.go.cd/blob/master/beta/plugin_upload.md)). I'm using a gocd docker container and it might differ a bit from a standard install, but I doubt it. 

This page [https://github.com/gocd/docs.go.cd/blob/master/beta/plugin_upload.md](https://github.com/gocd/docs.go.cd/blob/master/beta/plugin_upload.md) should be updated to reflect the correct property value.

**Comment by zabil** [comment]
This fix https://github.com/gocd/gocd/commit/a54d1c2 solves the problem from 16.8+ versions. It'll will accept ```Y``` and ```true```
