### ISSUE TITLE
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -e GO_SERVER_URL="https://<go-server-ip>:8154/go" <gocd-agent-image-with-docker>  where to find gocd-agent-image-with-docker?

### ISSUE THREAD

**Issue by vinothrao** [gocd/docs.go.cd#462]
https://docs.gocd.org/current/gocd_on_kubernetes/docker_workflows.html in this page it is mentioned that.

**Comment by arvindsv** [comment]
As mentioned in the `Drawbacks` section, it's a custom image that needs to be mentioned.
