### ISSUE TITLE
Minor Improvement to https://docs.gocd.org/22.1.0/configuration/dev_authentication.html

### ISSUE THREAD

**Issue by LittleSquish** [gocd/docs.go.cd#658]
I found the instructions slightly confusing as the example shows a relative path. 

Please indicate
1) Where the relative paths starts from,
2) That a fully qualified path may be used.

![image](https://user-images.githubusercontent.com/32883643/165950042-95372f0b-6640-4381-8188-ae1ac8dc9895.png)

**Comment by chadlwilson** [comment]
Hey there - sorry, I'm a bit confused since the example in the screenshot above shows an absolute/fully-qualified path (for a POSIX operating system) not a relative one. Which example are we talking about?

**Comment by LittleSquish** [comment]
Thanks for the reply.

I was not aware that this documentation was for posix. I was redirected here from a windows installation, the example shows a path that can be interpreted as a relative path within the windows environment.
I mentioned it here as it caused me some confusion during the installation.  Could you maybe add a comment to the article to say use a fully qualified path? It would have saved me some time.

Many thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chadlwilson** [comment]
Usually the direction of the `/` is a good hint :)

It's quite possible that a relative path works, but haven't tested that.
