### ISSUE TITLE
Add a note about the env vars that go sets by default.

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/docs.go.cd#91]
Add a note about environment variables such as GO_REVISION, GO_DEPENDENCY_LABEL etc that go sets by default, which could be used in the tasks.

**Comment by arvindsv** [comment]
Isn't this [here](https://docs.gocd.org/current/faq/dev_use_current_revision_in_build.html#standard-gocd-environment-variables) already?

**Comment by varshavaradarajan** [comment]
Oh. Wonder which repo I tried to find this in. :/ Will close this.
