### ISSUE TITLE
Update documentation to correct the information about TFS sdk and supported versions

### ISSUE THREAD

**Issue by jyotisingh** [gocd/docs.go.cd#99]
https://docs.gocd.org/current/configuration/tfs_config.html is outdated 

Some of the outdated info that I could find:
* `Go server and agent uses TFS Java SDK v10` 
* `TFS 2011 support has not been verified.`

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/docs.go.cd/pull/100
